services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=edildev
      - POSTGRES_PASSWORD=devsecret
      - POSTGRES_DB=edil_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DBLogFiles:/var/log/postgresql

    command:
      - "postgres"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/var/log/postgresql"
      - "-c"
      - "log_filename=postgres-%Y-%m-%d.log"
      - "-c"
      - "log_rotation_age=1d"
      - "-c"
      - "log_rotation_size=10MB"

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static_store:/var/www/static_store
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

volumes:
  pgdata: