spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/edil_db
    username: edildev
    password: devsecret

  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  cache:
    type: caffeine
    cache-names:
      - user_email_to_UUID
    caffeine:
      spec: expireAfterWrite=60m


jwt:
  secret: edil-secret-key-change-this-in-production-must-be-at-least-256-bits-long-for-hs256 #have to move to be a real key and move to the enviomenr variable assap
  expiration: 86400000

server:
  port: 8080
